# `dist` is a special directory in Actions.
# When you reference an action with `uses:` in a workflow,
# javascript files from `dist` will run.
# For our projects, we generate the dist through a build process from other source files.
# We need to make sure the checked-in innards of the `dist` directory actually matches what we expect it to be.
name: Check dist

on:
  workflow_call:
    inputs:
      dist-path:
        description: "Relative path to the dist folder"
        required: true
        type: string
      build-command:
        description: "Optional input to configure build command in case the default one doesn't suit"
        required: false
        type: string
        default: "npm run build"
      

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Rebuild the dist directory
        run: ${{inputs.build-command}}

      - name: Compare the expected and actual dist directories
        run: |
          if [ "$(git diff --ignore-space-at-eol ${{inputs.folder-path}} | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: ${{inputs.dist-path}}