name: Licensed

on:
  workflow_call:
    inputs:
      licensed-url:
        description: "Optional input to set the url of the required version of the Licenced tool"
        required: false
        type: string
        default: "https://github.com/github/licensed/releases/download/3.4.4/licensed-3.4.4-linux-x64.tar.gz"

jobs:
  validate-cached-dependency-records:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install licensed tool
        run: |
          cd $RUNNER_TEMP
          curl -Lfs -o licensed.tar.gz ${{inputs.licensed-url}}
          sudo tar -xzf licensed.tar.gz
          sudo mv licensed /usr/local/bin/licensed
          
      - name: Check cached dependency records
        run: licensed status