name: "Common workflow"

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set list of operating systems whick the workflow uses. Defaults to ['ubuntu-latest', 'windows-latest', 'macos-latest'] if not set"
        required: false
        type: string
        default: "['ubuntu-latest', 'windows-latest', 'macos-latest']"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ${{fromJson(inputs.operating-systems)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Install dependencies
      run: npm ci --ignore-scripts
      
    - name: Run linter
      run: npm run format-check

    - name: Build
      run: npm run build
      
    - name: Test
    - run: npm test